### ISSUE TITLE
updates to experiment text

### ISSUE THREAD

**Issue by scottbateman** [ncphillips/crowdstudy_writing_task#3]
Here are some updates from Carl:
- in second page of instructions, "After every 3 image" -> "After every 3 images"
- "answer a couple questions" -> "answer a few questions"
- in the summary, the third bullet point is just "Write...", should be the same as previous instructions

**Comment by ncphillips** [comment]
https://github.com/ncphillips/crowdstudy_writing_task/commit/09c0afd827426e70bec1a9cf562b3cbedca34f10
